### PR TITLE
Fix some respec issues

### PR DESCRIPTION
**Pull request by rmcilroy**
@igrigorik this fixes some respec issues in the spec. It is built upon the previous pull request, and I can't find a good way in GitHub to only show the difference between this PR and the base PR, but the actual change is the "Fix some respec issues" commit in this list (https://github.com/rmcilroy/requestidlecallback/commit/674d7e959267e5aa6306523b0cb79806c869a2af)

### CODE REVIEW

**Review by igrigorik — APPROVED** [review]
Great stuff, thanks Ross!

**Comment by igrigorik** [comment]
A related but non-blocking issue that we could take up in a separate PR, before we republish this: we should update the spec reference format recommended by @marcoscaceres in https://github.com/w3c/preload/pull/104#issuecomment-313508145. 

@siusin @rmcilroy do either of you have a few cycles to tackle that? Once that's resolved, I think we're ready to ship.

**Comment by rmcilroy** [comment]
Regarding the spec reference format - is it only the references to other specs (i.e., those with [Foo] which are defined to links at the bottom of index.html) which need changing here, or is there anything else?

**Comment by siusin** [comment]
@rmcilroy yes, it'd be great if you can add a Dependencies section ([example](https://w3c.github.io/preload/#dependencies)) to the document to maintain the refs that are currently at the bottom.

**Pull request merged**
