### PR TITLE
chore: auto-publish

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Review by yoavweiss — APPROVED** [review]
RSLGTM

**Comment by marcoscaceres** [comment]
Blocked on republishing. 

@caribouW3 @yoavweiss, what's the plan for this spec? Should we move it also back to CR too?

**Comment by yoavweiss** [comment]
For this one, it might be better to take it to REC and let it stay there, as I'm not aware of further plans to expand it. There are a few issues to be settled before that can happen.

**Comment by marcoscaceres** [comment]
Ok, cool. We can update this PR once the document goes to REC, and do periodic maintenance on the spec as needed.

**Comment by caribouW3** [comment]
The spec has to go back to CR first (the last PR ended up with a comment triggering significant change).

**Comment by marcoscaceres** [comment]
Thanks for clarifying @caribouW3. Ok, then this should still be useful for a few months after we go back to CR.

**Comment by caribouW3** [comment]
Returns to WD.
see #100

**Pull request merged**
