### PR TITLE
Add tests for requestIdleCallback.

### PR DESCRIPTION
**Pull request by rmcilroy**
Not sure if this is where you want to put tests, please let me know if there is a better place.

### CODE REVIEW

**Comment by igrigorik** [comment]
Hmm, I think these should probably live in https://github.com/w3c/web-platform-tests/

/cc @plehegar

**Comment by plehegar** [comment]
indeed. should go to web-platform-tests

**Comment by igrigorik** [comment]
Discussed on the call, these should live on w3c/web-platform-tests: https://github.com/w3c/web-platform-tests/#contributing

@rmcilroy can you redirect this there? :)

**Comment by rmcilroy** [comment]
Made a merge request at web-platform-tests at https://github.com/w3c/web-platform-tests/pull/2163. Please take a look, thanks.

**Pull request closed without merging**
